CREATE TABLE [dbo].[AreaAddress](
	[Id]		UNIQUEIDENTIFIER	NOT NULL,
	[Address]	NVARCHAR(4000)		NOT NULL,
	[AreaId]	UNIQUEIDENTIFIER	NOT NULL,
	CONSTRAINT [PK_AreaAddress] PRIMARY KEY CLUSTERED ([Id] ASC)
)