CREATE TABLE [dbo].[AreaDoctor](
	[Id]		INT					IDENTITY(1,1) NOT NULL,
	[AreaId]	UNIQUEIDENTIFIER	NOT NULL,
	[DoctorId]	UNIQUEIDENTIFIER	NOT NULL,
	CONSTRAINT [PK_AreaDoctor] PRIMARY KEY CLUSTERED ([Id] ASC)
)
