CREATE TABLE [dbo].[Doctor](
	[Id]			UNIQUEIDENTIFIER	NOT NULL,
	[FirstName]		NVARCHAR(255)		NULL,
	[SecondName]	NVARCHAR(255)		NULL,
	[LastName]		NVARCHAR(255)		NULL,
	[Deleted]		DATETIME			NULL,
	[SpecialityId]	UNIQUEIDENTIFIER	NULL,
	[DivLpuId]		UNIQUEIDENTIFIER	NULL,
	CONSTRAINT [PK_Doctor] PRIMARY KEY CLUSTERED ([Id] ASC)
)
